# Используем официальный образ Python 3.11 с "slim" версией (минимальный размер)
FROM python:3.13

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы зависимостей
COPY requirements.txt ./

# Устанавливаем зависимости с оптимизацией кэша
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы проекта (исключая то, что в .dockerignore)
COPY ./app .

# Открываем порт для FastAPI (по умолчанию 8000)
EXPOSE 8000

# Команда запуска сервера
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]